[package]
name = "oneprog-main"
version = "1.0.2-1"
authors = ["OneProg <jade.weirdo@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.7.3", features = ["fullstack"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]
